/**
 * src/lib/admin/types.ts
 *
 * Single source of truth for all admin panel types, constants, and pure
 * utility functions. Imported by both Backend (API routes, db layer) and
 * Frontend (admin UI components).
 *
 * Rules:
 *  - No Node.js-only imports (no 'fs', 'crypto', etc.) — this file must be
 *    importable in Edge runtime (middleware) and browser (client components).
 *  - No React imports — pure TypeScript.
 *  - No framer-motion or Tailwind — visual constants live in components.
 */

// ---------------------------------------------------------------------------
// Pipeline stages
// ---------------------------------------------------------------------------

/**
 * Ordered pipeline stages from first discovery to terminal state.
 * Order matters — UI renders columns in this order.
 */
export const PIPELINE_STAGES = [
  "Found",
  "Researched",
  "Emailed",
  "Called",
  "Follow-up",
  "Proposal",
  "Won",
  "Lost",
] as const;

export type PipelineStage = (typeof PIPELINE_STAGES)[number];

/**
 * Probability that a lead in this stage closes as Won.
 * Used for weighted pipeline value in analytics.
 */
export const STAGE_CLOSE_PROBABILITY: Record<PipelineStage, number> = {
  Found: 0.03,
  Researched: 0.08,
  Emailed: 0.12,
  Called: 0.25,
  "Follow-up": 0.35,
  Proposal: 0.6,
  Won: 1.0,
  Lost: 0.0,
};

/**
 * Stages considered "active" for pipeline value calculation.
 * Won and Lost are terminal and excluded from the active pipeline.
 */
export const ACTIVE_STAGES: PipelineStage[] = [
  "Found",
  "Researched",
  "Emailed",
  "Called",
  "Follow-up",
  "Proposal",
];

/** Terminal stages — no further stage progression expected. */
export const TERMINAL_STAGES: PipelineStage[] = ["Won", "Lost"];

/**
 * Average project value used for pipeline weighting.
 * Midpoint of NRG's typical $500–$1,100 project range.
 */
export const AVG_PROJECT_VALUE = 800;

// ---------------------------------------------------------------------------
// Scoring
// ---------------------------------------------------------------------------

/**
 * Four boolean factors that drive lead scoring.
 * Weights sum to 9.0 (max score).
 */
export const SCORE_WEIGHTS = {
  /** Bad or no existing website — clearest buying signal. */
  badOrNoWebsite: 3.0,
  /** Clearly making money — they can afford the project. */
  clearlyMakingMoney: 2.5,
  /** Easy to reach — contact info found; likely responsive. */
  easyToReach: 2.0,
  /** Good niche fit — restaurant, HVAC, law, salon. Noah's sweet spot. */
  goodNicheFit: 1.5,
} as const satisfies Record<string, number>;

export type ScoreFactors = {
  badOrNoWebsite: boolean;
  clearlyMakingMoney: boolean;
  easyToReach: boolean;
  goodNicheFit: boolean;
};

/**
 * Compute the lead score from its factor flags.
 * Returns a number in [0.0, 9.0].
 * Called on every Lead PATCH that touches scoreFactors.
 */
export function computeScore(factors: ScoreFactors): number {
  let score = 0;
  if (factors.badOrNoWebsite) score += SCORE_WEIGHTS.badOrNoWebsite;
  if (factors.clearlyMakingMoney) score += SCORE_WEIGHTS.clearlyMakingMoney;
  if (factors.easyToReach) score += SCORE_WEIGHTS.easyToReach;
  if (factors.goodNicheFit) score += SCORE_WEIGHTS.goodNicheFit;
  return score;
}

/**
 * Score thresholds for the hot/warm/cold badge.
 * Inclusive lower bound.
 */
export const SCORE_TIERS = {
  hot: 7,   // score >= 7
  warm: 4,  // score >= 4
  // cold: anything below 4
} as const;

export type ScoreTier = "hot" | "warm" | "cold";

export function getScoreTier(score: number): ScoreTier {
  if (score >= SCORE_TIERS.hot) return "hot";
  if (score >= SCORE_TIERS.warm) return "warm";
  return "cold";
}

// ---------------------------------------------------------------------------
// Stage history
// ---------------------------------------------------------------------------

/**
 * Immutable record of a single stage transition.
 * Append-only — never mutate existing entries.
 * `at` is an ISO 8601 string (new Date().toISOString()).
 *
 * Used for Phase-2 velocity analytics:
 *   time-in-stage = stageHistory[i+1].at - stageHistory[i].at
 */
export type StageHistoryEntry = {
  stage: PipelineStage;
  at: string; // ISO 8601
};

// ---------------------------------------------------------------------------
// Lead
// ---------------------------------------------------------------------------

export type Lead = {
  /** UUID v4, generated by crypto.randomUUID() at creation. */
  id: string;

  /** Business trading name. */
  businessName: string;

  /**
   * Industry / niche category.
   * Free-text but encouraged to be consistent: restaurant, HVAC, law, salon,
   * trades, retail, medical, other.
   */
  niche: string;

  /**
   * Houston neighborhood or city area (e.g. "Midtown", "Sugar Land", "Heights").
   * Used to prioritize local outreach.
   */
  neighborhood: string;

  /** Business phone number — copied to Client on conversion. */
  phone: string;

  /** Business or contact email — copied to Client on conversion. */
  email: string;

  /** Name of the decision-maker, if known. */
  contactName: string;

  /**
   * Free-form notes about the lead.
   * Prepended to Client.notes on conversion.
   */
  notes: string;

  /**
   * How the lead was discovered.
   * Free-text, e.g.: "Google Maps cold", "walk-in", "referral from X",
   * "inbound /contact form".
   * Kept raw for Phase-2 source-channel bucketing.
   */
  source: string;

  /** Current pipeline stage. */
  stage: PipelineStage;

  /**
   * Append-only log of all stage transitions.
   * First entry is always the creation stage (typically "Found").
   * Never mutate — only push new entries.
   */
  stageHistory: StageHistoryEntry[];

  /** Boolean factors driving the computed score. */
  scoreFactors: ScoreFactors;

  /**
   * Computed score in [0.0, 9.0].
   * Denormalized for fast sort/filter. Must be recomputed via computeScore()
   * whenever scoreFactors changes.
   */
  score: number;

  /**
   * Total number of meaningful outreach touches.
   * Incremented manually by owner, or auto-incremented when emailedAt/calledAt
   * are set via PATCH.
   */
  touchCount: number;

  /** ISO timestamp of the last email sent to this lead. Null if not yet emailed. */
  emailedAt: string | null;

  /** ISO timestamp of the last phone call to this lead. Null if not yet called. */
  calledAt: string | null;

  /**
   * ISO date string (YYYY-MM-DD) for the next scheduled follow-up.
   * Null if no follow-up is scheduled.
   * Used by the analytics endpoint to surface overdue/today follow-ups.
   */
  followUpAt: string | null;

  /**
   * Explicit follow-up needed flag. Independent of a specific date.
   * - true  → follow-up needed (with or without a date)
   * - false → no follow-up needed (followUpAt should also be null)
   * - undefined (existing leads) → infer from followUpAt !== null for back-compat
   */
  needsFollowUp?: boolean;

  /**
   * Short description of the next action to take.
   * E.g. "Send follow-up email", "Call back Tuesday", "Send proposal PDF".
   */
  nextActionNote: string;

  /**
   * Set to the Client.id after successful convert-to-client operation.
   * Null while lead is in pre-Won stages.
   * A non-null value does NOT mean the lead stage is Won — check stage too.
   */
  convertedClientId: string | null;

  /** ISO timestamp of lead creation. Set once at POST, never updated. */
  createdAt: string;

  /** ISO timestamp of last mutation. Updated on every PATCH. */
  updatedAt: string;
};

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

export type ClientStatus = "active" | "paused" | "churned";

export type Client = {
  /** UUID v4, generated by crypto.randomUUID() at creation. */
  id: string;

  /** Business trading name. */
  businessName: string;

  /** Primary contact name. */
  contactName: string;

  /** Business phone number. */
  phone: string;

  /** Business or contact email. */
  email: string;

  /** Live URL of the site NRG built. Empty string if not yet live. */
  siteUrl: string;

  /**
   * Recurring monthly charge in USD.
   * 0 if client has no monthly retainer (one-time project only).
   */
  monthlyCharge: number;

  /**
   * One-time project value in USD.
   * Includes design, build, and any one-time setup fees.
   */
  oneTimeValue: number;

  /** ISO date string (YYYY-MM-DD) of project start / first invoice. */
  startDate: string;

  /** Current engagement status. */
  status: ClientStatus;

  /**
   * ISO timestamp of the last invoice sent.
   * Null if never invoiced (client just created, or one-time project not yet billed).
   */
  lastInvoicedAt: string | null;

  /**
   * ISO timestamp of the last time NRG checked that the client's site is
   * still live and healthy.
   */
  lastVerifiedAt: string | null;

  /**
   * Free-form notes.
   * Pre-populated on conversion: "Converted from lead — " + Lead.notes
   */
  notes: string;

  /**
   * The Lead.id that this client was converted from.
   * Null for clients added directly without a lead record.
   * Used for Phase-2 source-channel revenue attribution.
   */
  sourceLeadId: string | null;

  /** ISO timestamp of client record creation. Set once, never updated. */
  createdAt: string;

  /** ISO timestamp of last mutation. Updated on every PATCH. */
  updatedAt: string;
};

// ---------------------------------------------------------------------------
// Analytics
// ---------------------------------------------------------------------------

/**
 * Full analytics payload returned by GET /api/admin/analytics.
 * All numbers. No strings except ISO timestamps in deferred fields.
 */
export type AnalyticsPayload = {
  // --- Revenue ---

  /** Sum of monthlyCharge for all clients with status === "active". */
  totalMrr: number;

  /** Sum of oneTimeValue for all clients (all statuses, all time). */
  totalOneTimeRevenue: number;

  /**
   * Average one-time project value.
   * totalOneTimeRevenue / total client count. 0 if no clients.
   */
  avgOneTimeValue: number;

  // --- Pipeline ---

  /**
   * Weighted pipeline value.
   * Sum over ACTIVE_STAGES leads: AVG_PROJECT_VALUE * STAGE_CLOSE_PROBABILITY[stage]
   */
  activePipelineValue: number;

  /** Count of leads in each stage. Every stage key is present (0 if none). */
  leadsByStage: Record<PipelineStage, number>;

  /** Total lead records (all stages, all time). */
  totalLeads: number;

  /** Total leads with stage === "Won". */
  totalWon: number;

  /** Total leads with stage === "Lost". */
  totalLost: number;

  /**
   * Win rate as a decimal (0–1).
   * totalWon / (totalWon + totalLost). Returns 0 if both are 0.
   */
  winRate: number;

  // --- Outreach ---

  /** Sum of touchCount across all leads. */
  totalTouches: number;

  /** Count of leads with emailedAt !== null. */
  leadsEmailed: number;

  /**
   * Email response rate as a decimal (0–1).
   * Numerator: leads in stages Called, Follow-up, Proposal, Won.
   * Denominator: leadsEmailed.
   * Returns null if leadsEmailed === 0.
   *
   * Phase-2: compare against benchmarks 3.43% avg / 5% good / 10% great.
   */
  emailResponseRate: number | null;

  // --- Clients ---

  /** Count of clients with status === "active". */
  activeClients: number;

  /** Count of clients with status === "paused". */
  pausedClients: number;

  /** Count of clients with status === "churned". */
  churnedClients: number;

  // --- Follow-up urgency ---

  /**
   * Count of leads where followUpAt < today's date (ISO YYYY-MM-DD),
   * and stage is not Won or Lost.
   * These are overdue — owner should action them.
   */
  overdueFollowUps: number;

  /**
   * Count of leads where followUpAt === today's date (ISO YYYY-MM-DD),
   * and stage is not Won or Lost.
   */
  followUpsToday: number;

  // --- Score distribution ---

  /** Leads with score >= SCORE_TIERS.hot (7). */
  hotLeads: number;

  /** Leads with score >= SCORE_TIERS.warm (4) and < SCORE_TIERS.hot (7). */
  warmLeads: number;

  /** Leads with score < SCORE_TIERS.warm (4). */
  coldLeads: number;
};

// ---------------------------------------------------------------------------
// API request/response shapes
// ---------------------------------------------------------------------------

/** Body for POST /api/admin/leads */
export type CreateLeadBody = Omit<
  Lead,
  "id" | "score" | "stageHistory" | "touchCount" | "convertedClientId" | "createdAt" | "updatedAt"
>;

/** Body for PATCH /api/admin/leads/[id] — all fields optional */
export type UpdateLeadBody = Partial<
  Omit<Lead, "id" | "score" | "stageHistory" | "createdAt">
>;

/** Body for POST /api/admin/clients */
export type CreateClientBody = Omit<
  Client,
  "id" | "createdAt" | "updatedAt"
>;

/** Body for PATCH /api/admin/clients/[id] — all fields optional */
export type UpdateClientBody = Partial<Omit<Client, "id" | "createdAt">>;

/** Body for POST /api/admin/leads/[id]/convert */
export type ConvertLeadBody = {
  monthlyCharge: number;
  oneTimeValue: number;
  siteUrl: string;
  startDate: string; // ISO YYYY-MM-DD
};

/** Response from POST /api/admin/leads/[id]/convert */
export type ConvertLeadResponse = {
  lead: Lead;
  client: Client;
};

/** Generic API error response shape */
export type ApiError = {
  error: string;
  details?: string;
};

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/**
 * Total lifetime value of a client.
 * One-time project value + (monthly charge * 12 months as proxy for a year).
 * Simple approximation — not account for churn date.
 */
export function lifetimeValue(client: Client): number {
  return client.oneTimeValue + client.monthlyCharge * 12;
}

/**
 * Returns true when a lead has an active follow-up requirement.
 * Respects the explicit `needsFollowUp` flag when set; otherwise infers
 * from `followUpAt !== null` for backward compatibility with existing leads.
 */
export function isFollowUpNeeded(lead: Lead): boolean {
  return lead.needsFollowUp ?? (lead.followUpAt !== null);
}

/**
 * Today's date as an ISO YYYY-MM-DD string (in local time).
 * Used for follow-up overdue/today calculations.
 * Note: runs in Node.js context — uses local server time zone.
 */
export function todayIso(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
